- .gitignore
- gms-services/pom.xml
- gms-user-interface/pom.xml
- pom.xml
This is initial structure for the GMS project.
> GMS Structure

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/config/dashboard.client.config.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/config/dashboard.client.routes.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/controllers/components/awarded-grants.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/controllers/components/unawarded-grants.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/controllers/dashboard.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/dashboard.client.module.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/module_config/resources/en.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/services/dashboard.client.service.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/views/components/awarded-grants.client.view.html
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/views/components/unawarded-grants.client.view.html
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/views/dashboard-title.client.view.html
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/views/dashboard.client.view.html
Dashboard widgets for GMS. Still need to modify few stuff when the project takes shape but this is just a base.
> AFDP-1483 Dashboard Widget - Awarded Grants Dashboard Status

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/controllers/components/awarded-grants.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/controllers/components/unawarded-grants.client.controller.js
> dashboard-fix

- gms-services/src/main/java/com/arkcase/gms/service/form/SubmissionFormService.java
- gms-services/src/main/resources/documentation/acm-forms.properties
1. Added setter that cause problem while starting the app
2. Added needed properties for Evaluation form
Action needed:
1. Please update property `plain_configuration.COMPLAINT.properties` in the **$HOME/.acm/acm-forms.properties** with the following data (concatenate them to the existing - comma separated):
`grant.caseNumber=grant.caseNumber,grant.title=grant.title,grant.details=grant.details`
> Added setter and needed properties for Evaluation form

- gms-services/src/main/resources/ddl/tables/decision-db-tables-1.0.xml
I have added new column in the JPA object but forgot to add change set in liquibase. This commit contains new file with change set for that missing column
> Adding missing column in the database

- gms-services/src/main/resources/spring/spring-library-frevvo-form.xml
> Adding plain service to the Frevvo form services

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/reports/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/reports/module_config/resources/en.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/budget/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/payment/module_config/config.json
- Fixed position for budget/payment modules in the topbar. 
- Fixed report state label
> Position and label fixes

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/cases/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/complaints/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/award.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-documents.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-main.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/views/award.client.view.html
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/views/components/award-main.client.view.html
Implement landing page from core. Change labels and config to match core changes.
> track core changes and make appropriate code changes.

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/cases/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/complaints/module_config/config.json
1. Change ‘Unawarded Grants’ to ‘Grant Opportunity’
2. Change ‘Submissions’ to ‘Applications’
> Label changes for modules Unawarded Grant and Submissions

- pom.xml
Updating latest ArkCase version
> AFDP-1660: Updating ArkCase version

- gms-services/src/main/java/com/arkcase/gms/model/GmsConstants.java
- gms-services/src/main/java/com/arkcase/gms/service/form/SubmissionCompletedWorkflowListener.java
- gms-services/src/main/resources/spring/spring-library-frevvo-form.xml
The whole logic from Maksud I've changed. There was several places that needed refactoring.
> AFDP-1661: Fixing bug while approving task

- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/award-list.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/award.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-actions.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-correspondence.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-cost.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-details.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-documents.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-history.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-info.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-main.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-notes.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-participants.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-people.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-references.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-tasks.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-time.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/views/award.client.view.html
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/views/components/award-correspondence.client.view.html
With lates changes for ArkCase core application, Awards module was not workin. This PR fix that.
> AFDP-1678: Awards module - Tree view doesn't work

- gms-services/src/main/resources/spring/spring-library-complaint.xml
First PR https://github.com/Armedia/ACM3/pull/1198 should be merged. After that i will merge this PR.
> AFDP-1666: Override properties while closing complaint

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/services/dashboard.client.service.js
My Tasks widget was now showing up for Ann or Samuel users. Also My Complaints was not showing up. This PR fix that.
> AFDP-1665: Dashboard - My Task Widget - Not tasks showing up

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/audit/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/notifications/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/notifications/module_config/resources/en.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/payment/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/payment/module_config/resources/en.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/subscriptions/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/subscriptions/module_config/resources/en.json
Make config.json for Audit, Payment, Subscriptions and Notifications modules empty - on that way we are hiding them
> AFDP-1671: Hiding Audit, Payment, Subscriptions and Notifications modules

- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/budget/controllers/components/budget-info.client.controller.js
Small fix for parent info redirect for Expenditures module.
> small fix for parent info for expenditures

- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/budget/module_config/config.json
> icons for budget module

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/controllers/components/awarded-grants.client.controller.js
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/module_config/config.json
Changes in config.json for awardad and un-awarded dashboard widgets.
> AFDP-1483: Dashboard Widgets - columns fixes

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/cases/module_config/config.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/cases/module_config/resources/en.json
- gms-user-interface/src/main/resources/META-INF/resources/resources/modules/award/controllers/components/award-actions.client.controller.js
This PR is about fixing merge button for Grant Opportunity and Awards. Please review first this PR https://github.com/Armedia/ACM3/pull/1210 , and after that one is merged this PR can be marged.
> Merge button was not working.

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/search/module_config/config.json
In Search module the date created has the wrong format and the search results should have hyperlinks. This PR fix that.
> AFDP-1692: Search Module - Issues

- gms-user-interface/src/main/resources/META-INF/resources/resources/custom_modules/dashboard/module_config/config.json
Fix for Grant Opportunities Widget, there much space on the right.
> AFDP-1483: Grant Opportunities Widget fix

- gms-services/src/main/java/com/arkcase/gms/service/ReviewRequestService.java
Adding object (target) types where we invoke some methods because the core application is changed. The change is here: https://github.com/Armedia/ACM3/pull/1214.
> AFDP-1686: Making needed changes because core application was changed

- gms-services/src/main/java/com/arkcase/gms/model/Grant.java
- gms-services/src/main/java/com/arkcase/gms/service/form/CostBudgetListener.java
- gms-services/src/main/java/com/arkcase/gms/transformer/GrantToSolrTransformer.java
- gms-services/src/main/resources/ddl/tables/grant-db-tables-1.0.xml
- gms-services/src/main/resources/spring/spring-library-gms.xml
Calculate award remaining value while adding expenditures. Add it to Solr as well.
> Calculate award remaining value
